### ISSUE TITLE
note hard-coded machine type, location

### ISSUE THREAD

**Issue by vielmetti** [hassy/packet-performance-labs#1]
Would be worth a note in the README at least that the setup as provided has "ams1" hard-coded as a Packet location, and that if you were going to run this against a different data center you'd need to change that.

**Comment by hassy** [comment]
Thanks @vielmetti. Fixed in https://github.com/hassy/packet-performance-labs/commit/6d5c07fea916028b6ce60217c1c5bb5e127d15e7 Both facility and server type can be customized now.
